${EE_SIDE_PREFIX}_controller:
  ros_parameters:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - ${EE_SIDE_PREFIX}_finger_joint

    constraints:
      goal_time: &goal_time_constraint 0.6
      stopped_velocity_tolerance: &stopped_velocity_constraint 5.0
      ${EE_SIDE_PREFIX}_finger_joint:
        goal: 0.02
